volumes:
  grav-prod:
    driver: local
    driver_opts:
      type: none
      device: $PROJECT_ROOT/grav
      o: bind

services:
  grav-prod:
    build: ./
    ports:
      - 80:80
    volumes:
      - grav-prod:/var/www/html
