volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: $PROJECT_ROOT/grav-admin
      o: bind

services:
  grav-dev:
    build: ./
    ports:
      - 8080:80
    volumes:
      - grav-data:/var/www/html
